const PERMISSIONS = {
  DASHBOARD: "dashboard",
  PROJECTS: "projects",
  PLOTS: "plots",
  CUSTOMERS: "customers",
  SUPPLIERS: "suppliers",
  ITEMS: "items",
  CHART_OF_ACCOUNTS: "chartOfAccounts",
  SALES_INVOICE: "salesInvoice",
  PURCHASE_ENTRY: "purchaseEntry",
  CASH_PAYMENT: "cashPayment",
  BANK_PAYMENT: "bankPayment",
  REPORTS: "reports",
  USERS: "users",
  ACCOUNTING: "accounting",
  FINANCE: "finance",
  CRM: "crm",
  HR: "hr",
  DOCUMENTS: "documents",
  ANALYTICS: "analytics",
};

const OPERATOR_PERMISSIONS = [
  PERMISSIONS.DASHBOARD,
  PERMISSIONS.PROJECTS,
  PERMISSIONS.PLOTS,
  PERMISSIONS.CUSTOMERS,
  PERMISSIONS.SUPPLIERS,
  PERMISSIONS.ITEMS,
  PERMISSIONS.SALES_INVOICE,
  PERMISSIONS.PURCHASE_ENTRY,
  PERMISSIONS.CASH_PAYMENT,
  PERMISSIONS.BANK_PAYMENT,
];

PERMISSIONS.OPERATOR_PERMISSIONS = OPERATOR_PERMISSIONS;

module.exports = PERMISSIONS;
